### ISSUE TITLE
Cannot use with Windows 11...

### ISSUE THREAD

**Issue by livxy** [DataDog/guarddog#135]
After installing using the recommended way, `pip install guarddog`, and then running a `python -m guarddog`, I get hit with an error:
 
 ```bash
 C:\Users\aidan>python -m guarddog

Traceback (most recent call last):
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\site-packages\guarddog\__init__.py", line 1, in <module>
    from guarddog.scanners.package_scanner import PackageScanner  # NOQA
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\site-packages\guarddog\scanners\package_scanner.py", line 8, in <module>
    from guarddog.analyzer.analyzer import Analyzer
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\site-packages\guarddog\analyzer\analyzer.py", line 4, in <module>
    from semgrep.semgrep_main import invoke_semgrep  # type: ignore
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\site-packages\semgrep\semgrep_main.py", line 25, in <module>
    from semgrep.core_runner import CoreRunner
  File "C:\Users\aidan\AppData\Local\Programs\Python\Python310\lib\site-packages\semgrep\core_runner.py", line 5, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

I am familiar with resource, `resource` is built in on UNIX systems... Not on Windows :(

It seems as if it **MUST** require a UNIX-based operating system to run Guarddog, as Semgrep doesn't have any installation methods for Windows, [other than WSL](https://semgrep.dev/docs/getting-started/), which means I would have to move _**ALL**_ of my files over to the WSL... Doesn't sound fun.

Is there anyway I can get around this?

**Comment by livxy** [comment]
Edit found a temporary fix using a modified approach at Docker:

```bat
docker pull ghcr.io/datadog/guarddog
doskey guarddog=docker run --rm ghcr.io/datadog/guarddog
```

**Comment by christophetd** [comment]
Thanks for reporting! Will add a note about this in the docs.

**Comment by livxy** [comment]
Bump! 
- added new commands for the `alias` since `doskey` is not working.
- removed `& REM` since they don't work on a terminal without being inside a Batch file.
