### ISSUE TITLE
PyPi Sarif Formatting broken in 1.4.0

### ISSUE THREAD

**Issue by AngellusMortis** [DataDog/guarddog#285]
It looks like the issue was most likely introduce by this PR: https://github.com/DataDog/guarddog/pull/279

Downgrading to 1.3.0 fixes the issue (confirmed multiple times)

Reproducible with simple requirements file:

```
requests==2.31.0
```

```bash
$ guarddog pypi verify --output-format sarif test-requirements.txt 
/usr/local/lib/python3.10/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
Scanning using at most 20 parallel worker threads
Traceback (most recent call last):
  File "/usr/local/bin/guarddog", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/guarddog/cli.py", line 297, in verify_pypi
    return _verify(target, rules, exclude_rules, output_format, exit_non_zero_on_finding, ECOSYSTEM.PYPI)
  File "/usr/local/lib/python3.10/site-packages/guarddog/cli.py", line 152, in _verify
    return_value = report_verify_sarif(path, list(rule_param), results, ecosystem)
TypeError: 'NoneType' object is not iterable
```

**Comment by christophetd** [comment]
fixed by #286
