### ISSUE TITLE
Python 3.9 pinned, but guarddog uses Python 3.10 syntax

### ISSUE THREAD

**Issue by zmallen** [DataDog/guarddog#93]
## Description
Guarddog specifies python >=3.9 in the `pyproject.toml` file, but syntax in guarddog is python 3.10.

## How to reproduce
Install python (I use pyenv) >= 3.9 < 3.10

```
└> pyenv global 3.9.9
└> python --version
Python 3.9.9
```

```bash
cd /path/to/guarddog && poetry install &&poetry run guarddog
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zack.allen/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zack.allen/git/guarddog/guarddog/cli.py", line 15, in <module>
    from .scanners.project_scanner import RequirementsScanner
  File "/Users/zack.allen/git/guarddog/guarddog/scanners/project_scanner.py", line 116
    match qualifier:
          ^
SyntaxError: invalid syntax
```

Since poetry is just a wrapper to manage pip venvs (and a bit more), same behavior works for `pip install`

```bash
pip install -r requirements.txt
python -m guarddog
└> python -m guarddog
Traceback (most recent call last):
  File "/Users/zack.allen/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/zack.allen/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/zack.allen/git/guarddog/guarddog/__main__.py", line 5, in <module>
    import guarddog.cli
  File "/Users/zack.allen/git/guarddog/guarddog/cli.py", line 15, in <module>
    from .scanners.project_scanner import RequirementsScanner
  File "/Users/zack.allen/git/guarddog/guarddog/scanners/project_scanner.py", line 116
    match qualifier:
          ^
SyntaxError: invalid syntax
```

**Comment by zmallen** [comment]
```bash
└> pyenv global 3.10.0
└> python --version
Python 3.10.0
```

Drop into venv or use poetry

```bash
└> poetry env use 3.10.0
Creating virtualenv guarddog-mCelS2pb-py3.10 in /Users/zack.allen/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/zack.allen/Library/Caches/pypoetry/virtualenvs/guarddog-mCelS2pb-py3.10
└> poetry run guarddog
Usage: guarddog [OPTIONS] COMMAND [ARGS]...

  Guard Dog cli tool to detect PyPI malware

Options:
  --help  Show this message and exit.

Commands:
  scan    Scan a package
  verify  Verify a requirements.txt file
```
works!
